### ISSUE TITLE
setBreaksEnabled in the config file

### ISSUE THREAD

**Issue by Vinze** [AlfredoRamos/parsedown-extra-laravel#2]
Is it possible to set the `setBreaksEnabled` option somewhere globally? I tried putting this to the parsedownextra.php file but that didn't work.

**Comment by AlfredoRamos** [comment]
No, at least not right now, you can still set the option but you might need to edit files. Example:

**test.blade.php**
```php
Markdown::setBreaksEnabled(true)->parse("Some\ntext")
```

Is that enough for you? If not I'll think what would be the best way to do it, not just for that option but all of them :sunglasses:
