### ISSUE TITLE
Don't use t.co in HostBlackList

### ISSUE THREAD

**Issue by captain-torche** [AlfredoRamos/parsedown-extra-laravel#3]
As [HTML Purifier's HostBlacklist](http://htmlpurifier.org/live/configdoc/plain.html#URI.HostBlacklist) only manages to check the presence of each string on the current domain name, the use of t.co in the filters list leads to too many false positives, since it will match every .com (or .co.uk and so on) ending by a single "t".

At least, t.co should be removed from config/parsedown.php

**Comment by AlfredoRamos** [comment]
I haven't run into that problem but yeah, I think blocking that string in a domain could cause more problems that benefits.

It has been already removed in the master branch.

**Comment by captain-torche** [comment]
Thanks !
