### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by bonny** [AlfredoRamos/parsedown-extra-laravel#30]
When using Laravel 9 and PHP 8.1 I get this error – and yes, I know it was just released! :)

`illuminate/filesystem[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.`

Perhaps due to changes to https://laravel.com/docs/9.x/upgrade#flysystem-3.

**Comment by AlfredoRamos** [comment]
Hi :wave:

It should work now.

I was waiting for the testing framework I'm using to be upgraded.

> Perhaps due to changes to https://laravel.com/docs/9.x/upgrade#flysystem-3

Fortunately that's handled by `illuminate/filesystem` so no changes were needed.
