### ISSUE TITLE
How do you completely disable HTML Purifier?

### ISSUE THREAD

**Issue by photonstorm** [AlfredoRamos/parsedown-extra-laravel#37]
I don't want to run the HTML through Purifier, so I tried to disable it via the config, but no luck:

```php
        $html = markdown($doc->body(),
            [
            'purifier' => [
                'enabled' => false
                ]
            ]
        );
```

What's the correct way to do this?

**Comment by AlfredoRamos** [comment]
> What's the correct way to do this?

@photonstorm You can see how to temporarily disable it in the [Helper](https://github.com/AlfredoRamos/parsedown-extra-laravel#helper) section on the README.

```php
markdown('Hello world', ['purifier' => false])
```

Note that the `enabled` key is not passed when using the facade or the `markdown()` helper function.

However, if you don't want it enabled anywhere, you can completely turn off in the configuration file by setting this key to `false` ([ref](https://github.com/AlfredoRamos/parsedown-extra-laravel/blob/a8c3379750dd4bb7716aac2dffaa315b345a9b2e/config/parsedownextra.php#LL5C19-L5C19)):

```php
[
	'purifier'	=> [
		'enabled'	=> false,
	# Other config keys...
]
```

Please check the [Configuration](https://github.com/AlfredoRamos/parsedown-extra-laravel#configuration) section for instructions to create a copy of the config file.

**Comment by photonstorm** [comment]
Thanks for explaining! I honestly feel your answer is so useful it should be part of the README. Especially how you cannot do `enabled: false` in the config when using the helper function, as that was the first thing I tried.

I've run into loads of problems with HTML Purifier being tyrannical on perfectly valid content (the less said about its treatments of iframes, the better), so this was a last resort but solved everything.
