### ISSUE TITLE
The Markdown::parse() method is announced as deprecated

### ISSUE THREAD

**Issue by Okipa** [AlfredoRamos/parsedown-extra-laravel#4]
The `Markdown::parse()` method is announced as deprecated.
We find the following information into the PHPdoc :
```
@deprecated Function overloaded to maintain compatibility.
```
Which other method should we use to avoid problems in the future versions ?

**Comment by AlfredoRamos** [comment]
I'm using an overloaded `Parsedown` method to sanitize the HTML, the `@deprecated` PHPDoc tag is not really needed so I will remove it.

There's no alternative method if you want to use HTML Purifier too, if you don't need it you might want to use `Markdown::text()`
