### ISSUE TITLE
Compatibility to laravel 5.5

### ISSUE THREAD

**Issue by xdisplayx** [AlfredoRamos/parsedown-extra-laravel#5]
Hello! Could you add the compatibility to laravel 5.5?
Thank you!

**Comment by AlfredoRamos** [comment]
It currently supports the development version of Laravel 5.5 in the [v0.7.x](https://github.com/AlfredoRamos/parsedown-extra-laravel/tree/v0.7.x) branch.

```json
"alfredo-ramos/parsedown-extra-laravel": "v0.7.x-dev"
```

**Comment by xdisplayx** [comment]
Laravel 5.5 ya no esta en desarrollo, https://laravel.com/docs/5.5/upgrade.

When trying to update another compatibility error comes out.

Problem 1
    - The requested package alfredo-ramos/parsedown-extra-laravel ~0.7.0 is satisfiable by alfredo-ramos/parsedown-extra-laravel[v0.7.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package laravel/framework 5.5.* is satisfiable by laravel/framework[5.5.x-dev] but these conflict with your requirements or minimum-stability.


Thank you!

**Comment by AlfredoRamos** [comment]
Yes, the docs have been updated but It has not been released yet:

- https://github.com/laravel/framework/releases
- https://github.com/laravel/laravel/releases
- https://packagist.org/packages/laravel/laravel
- https://packagist.org/packages/laravel/framework
- https://github.com/laravel/framework/blob/master/CHANGELOG-5.5.md

**Comment by xdisplayx** [comment]
Ok very well, but how to solve these errors to update following the documentation guide?

 "require": {
        "php": ">=7.0.0",
        "alfredo-ramos/parsedown-extra-laravel": "~0.7.0",
        "laravel/framework": "5.5.*",
...
}

Problem 1
- The requested package alfredo-ramos/parsedown-extra-laravel ~0.7.0 is satisfiable by alfredo-ramos/parsedown-extra-laravel[v0.7.x-dev] but these conflict with your requirements or minimum-stability.
Problem 2
- The requested package laravel/framework 5.5.* is satisfiable by laravel/framework[5.5.x-dev] but these conflict with your requirements or minimum-stability.

Thank you!

**Comment by AlfredoRamos** [comment]
@xdisplayx 

> The error is says that you're trying to use a development version in a stable Laravel version.

You can solve it by using a development version of Laravel, see [schema#minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) and [schema#prefer-stable](https://getcomposer.org/doc/04-schema.md#prefer-stable).

If you wan't to use this in a production environment, please wait until Laravel 5.5 is released, I will release a new version shortly after and this won't be a problem anymore.

**Comment by AlfredoRamos** [comment]
As previously said, `0.7.x` branch has been merged into `master` branch, and version `0.7.0` has been released.
